# Generated by Django 5.1.6 on 2025-03-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0003_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='drugs',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='drug',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
