# Generated by Django 5.1.6 on 2025-03-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_sale',
            field=models.BooleanField(default=False),
        ),
    ]
